### ISSUE TITLE
Save token in HopController?

### ISSUE THREAD

**Issue by chrislong** [tellisnz/collared-kerberos#1]
This repo is a great example, thanks! I'd like to do something different with the endpoint (i.e., HopController) besides connect to a website, though: I'd like to save the credentials in a credential cache for use by another application (a standalone one that would be extremely difficult to modify). Could you give me any pointers on how to turn the `token` byte array into a credential cache?

Thanks!

**Comment by tellisnz** [comment]
I guess there isn't anything stopping you from caching them, but not they are a short lived service ticket, that clients will always present to you anyway. When you say 'using them by another app' you'd have to have this app reuse the auth details/tgt of the current app that is accepting the token (the hop controller) as these are tied.

So not really sure it makes much sense to do this - maybe you could elaborate a bit more on your use case?

**Comment by chrislong** [comment]
I have a back-end server that needs to mount files from a Windows file share, and it needs to get the user credentials from a front-end server the user interacts with. It involves S4U2Proxy, so I need to use the GSS API. I was stuck on getting credentials in Java and saving them to a ccache file so mount.cifs could use them. Since my original comment here, I have taken the approach of using the GSS C API via JNA, because the C API can save credentials in a file.
